const fs = require('fs');
const path = require('path');

// Target hook file
// We assume we are in .agent/skills/skills/daily-work-tracker/scripts/
// So we go up 5 levels to find .git? 
// No, let's look for the root dynamically or assume standard structure.
// The user workspace is e:\X00_xiqiuqiu\frontend-toc
// So .git is at e:\X00_xiqiuqiu\frontend-toc\.git

// We can try to find the git root
const findGitRoot = (startDir) => {
    // Prefer the current working directory if it is a git root and we are inside it
    const cwd = process.cwd();
    if (fs.existsSync(path.join(cwd, '.git'))) {
        return cwd;
    }

    let current = startDir;
    while (current !== path.parse(current).root) {
        if (fs.existsSync(path.join(current, '.git'))) {
            return current;
        }
        current = path.dirname(current);
    }
    return null;
};

const root = findGitRoot(__dirname);
if (!root) {
    console.error("Could not find git root.");
    process.exit(1);
}

const hookDir = path.join(root, '.git', 'hooks');
if (!fs.existsSync(hookDir)) {
    console.error(".git/hooks directory not found.");
    process.exit(1);
}

const hookFile = path.join(hookDir, 'post-commit');

// The relative path from root to the handler
// We know __dirname is absolute.
const relativeHandlerPath = path.relative(root, path.join(__dirname, 'post-commit-handler.cjs')).replace(/\\/g, '/');

const hookContent = `#!/bin/sh
# Daily Work Tracker Hook
# Generated by daily-work-tracker skill

# Ensure interactivity (critical for Windows Git Bash / generic shells)
exec < /dev/tty

# Check if node is available
if command -v node >/dev/null 2>&1; then
    node "${relativeHandlerPath}"
else
    echo "Node.js not found in path. Skipping work log."
fi
`;

fs.writeFileSync(hookFile, hookContent);
try {
    fs.chmodSync(hookFile, '755');
} catch (e) {
    // Ignored on Windows usually
}

console.log(`Successfully installed post-commit hook at ${hookFile}`);
console.log(`Pointing to: ${relativeHandlerPath}`);
